### ISSUE TITLE
No issues just had to request something.

### ISSUE THREAD

**Issue by ohmichael** [audiosistem/Bee-Queen#1]
I have friends who would love your addon but we speak English - is there anyway to get an English translated version of your torrent addon “Movies RO Sites Pack”?

**Comment by audiosistem** [comment]
> I have friends who would love your addon but we speak English - is there anyway to get an English translated version of your torrent addon “Movies RO Sites Pack”?

![MRSP](https://user-images.githubusercontent.com/6246768/121624288-eb273180-ca79-11eb-80da-3c4ba0703322.jpg)

**Comment by audiosistem** [comment]
![eng](https://user-images.githubusercontent.com/6246768/121624608-83bdb180-ca7a-11eb-83e1-6a5b0d308d00.jpg)

**Comment by audiosistem** [comment]
![Open](https://user-images.githubusercontent.com/6246768/121624639-8ae4bf80-ca7a-11eb-9ee9-13693ba3965c.jpg)

**Comment by audiosistem** [comment]
![Open 2](https://user-images.githubusercontent.com/6246768/121624782-ce3f2e00-ca7a-11eb-808b-285cd3559d35.jpg)

**Comment by ohmichael** [comment]
Ok thank you

**Comment by audiosistem** [comment]
In widget(Video)you can't change.Romanian subtitles included.You can change with another source. Have a good day!
